Pioneer:
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Velocity Controllers ---------------------------------------
ruedaizq_del_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: base_ruedaizqdel_joint


ruedader_del_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: base_ruedaderdel_joint


ruedaizq_tra_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: base_ruedaizqtra_joint


ruedader_tra_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: base_ruedadertra_joint

